### ISSUE TITLE
Allow setting  ingress.class

### ISSUE THREAD

**Issue by cbuckley01** [cloudflare/cloudflare-ingress-controller#30]
To allow multiple ingresses for multiple domains we need to be able to set the ingress.class on the ingress controller to map service -> controller with multiple agro Ingress controllers in a cluster.

**Comment by cbuckley01** [comment]
That is my primary use case at this time and that would be quite useful.  But also the ability to set the ingress class like the nginx ingress (with  --ingress-class) allows for multiple controllers in the same cluster which has many use cases in multi-app/namespace high volume cluster scenarios.

**Comment by ntfrnzn** [comment]
Going to elaborate on this here and make notes and references.

https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/multiple-ingress-controllers describes how to run multiple ingress controller types in a particular cluster, with the expectation that the ingress controller has a class key and will attend only to ingresses that match.  The argo-tunnel controller specifies it here https://github.com/cloudflare/cloudflare-ingress-controller/blob/8df5e2cc90d8428aac05c7cebc59045f5ce45a02/pkg/controller/controller.go#L29
By default the nginx controller uses a value of "nginx"

However, the nginx ingress controller allows you to redefine that value at start time with a command-line flag, 	https://github.com/kubernetes/ingress-nginx/blob/238ad76d65ea0383c1a3f80a2bc76a80e9399161/cmd/nginx/flags.go#L55 so you can use arbitrary values that are different for each deployment.  (If I had implemented that feature, I would have defined a new annotation key along the lines of https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md and not re-used "kubernetes.io/ingress.class", YMMV)  

Because the argo-tunnel functionality depends on a cloudflare account secret and a cloudflare domain, there's a different path for fanning out.  We can

 - have a single ingress controller in a namespace that has multiple domain secrets
 - have different ingress controllers in different namespaces each with separate domain secrets
 - specify that the ingress controller only attend to domains that match a command-line value (whether the secret is present or not).

**Comment by ntfrnzn** [comment]
https://github.com/cloudflare/cloudflare-ingress-controller/pull/39 provides this functionality
