### ISSUE TITLE
Support for multiple namespaces

### ISSUE THREAD

**Issue by koalalorenzo** [cloudflare/cloudflare-ingress-controller#9]
Is to support multiple namespaces (aka, like a traditional ingress controller) in the roadmap?
Alternatively, how can I tunnel my NGINX ingress controller inside the warp, and keep configuring only nginx ingresses? Can I set up a wildcard hostname for the warp somehow?

**Comment by ntfrnzn** [comment]
The namespaces form a natural security boundary for multi-tenant clusters.  The warp authentication tokens allow the ability to create tunnels (i.e. use the cloudflare account) and are stored within namespaces. Because of the security concerns, it seems not unnatural to use multiple warp ingress controllers in multiple namespaces.

I don't think I understand the question about mixing nginx and warp controllers.  Maybe that can go into a different issue.

**Comment by rabbitfang** [comment]
Namespaces are not always used as a security boundary between multiple tenants. They are often (such as in my case) used as a logical separation between different applications. It would be nice to be able to have a single warp controller that serves multiple namespaces. I think the option to restrict the controller to specific namespaces should be left to the user.

**Comment by koalalorenzo** [comment]
I agree, the user should be in charge of how to use the cluster and how to set the security boundaries.

**Comment by ntfrnzn** [comment]
implemented and resolved with https://github.com/cloudflare/cloudflare-ingress-controller/pull/19
